{
  "schema": "bh.v1.transcripts",
  "schema_version": "1.0.0",
  "step_id": "02_transcribe_asr_adapter",
  "step_run_id": "01K6CRWTMHGZK6B9R5NTS0QHBJ",
  "flow_run_id": null,
  "producer": {
    "git_sha": "593c4e1",
    "host": "SERVIS-MCAREK",
    "user": "MCarek",
    "processor_version": null
  },
  "run_mode": "incr",
  "started_at_utc": "2025-09-30T07:37:51Z",
  "finished_at_utc": "2025-09-30T07:37:51Z",
  "status": "partial",
  "input_refs": [],
  "outputs": {
    "primary": "transcripts_recordings.jsonl",
    "aux": {
      "call_level": "transcripts_calls.jsonl"
    }
  },
  "counts": {
    "recordings": 1,
    "transcribed": 0,
    "failed": 1,
    "segments": 0
  },
  "metrics": {
    "avg_segments_per_recording": 0,
    "throughput_records_per_min": 0.0
  },
  "errors": [
    {
      "unit_id": "193c444a-7e91-11f0-a473-2f775d7c125b",
      "error_key": "RuntimeError: Transcriber selhal: C:\\Users\\MCarek\\bh-rag\\Moje_Python_projekty\\spinoco-download\\venv\\Scripts\\python.exe: can't open file 'C:\\\\Users\\\\MCarek\\\\bh-rag\\\\Moje_Python_projekty\\\\spinoco-whisper\\\\main.py': [Errno 2] No such file or directory\n\\nTraceback (most recent call last):\n  File \"C:\\Users\\MCarek\\bh-rag\\Moje_Python_projekty\\spinoco-download\\steps\\transcribe_asr_adapter\\run.py\", line 378, in _transcribe_worker\n    transcript_path = self.run_transcriber(audio_path, temp_output_dir)\n  File \"C:\\Users\\MCarek\\bh-rag\\Moje_Python_projekty\\spinoco-download\\steps\\transcribe_asr_adapter\\run.py\", line 281, in run_transcriber\n    raise RuntimeError(f\"Transcriber selhal: {result.stderr}\")\nRuntimeError: Transcriber selhal: C:\\Users\\MCarek\\bh-rag\\Moje_Python_projekty\\spinoco-download\\venv\\Scripts\\python.exe: can't open file 'C:\\\\Users\\\\MCarek\\\\bh-rag\\\\Moje_Python_projekty\\\\spinoco-whisper\\\\main.py': [Errno 2] No such file or directory\n\n",
      "message": "Transcription failed: RuntimeError: Transcriber selhal: C:\\Users\\MCarek\\bh-rag\\Moje_Python_projekty\\spinoco-download\\venv\\Scripts\\python.exe: can't open file 'C:\\\\Users\\\\MCarek\\\\bh-rag\\\\Moje_Python_projekty\\\\spinoco-whisper\\\\main.py': [Errno 2] No such file or directory\n\\nTraceback (most recent call last):\n  File \"C:\\Users\\MCarek\\bh-rag\\Moje_Python_projekty\\spinoco-download\\steps\\transcribe_asr_adapter\\run.py\", line 378, in _transcribe_worker\n    transcript_path = self.run_transcriber(audio_path, temp_output_dir)\n  File \"C:\\Users\\MCarek\\bh-rag\\Moje_Python_projekty\\spinoco-download\\steps\\transcribe_asr_adapter\\run.py\", line 281, in run_transcriber\n    raise RuntimeError(f\"Transcriber selhal: {result.stderr}\")\nRuntimeError: Transcriber selhal: C:\\Users\\MCarek\\bh-rag\\Moje_Python_projekty\\spinoco-download\\venv\\Scripts\\python.exe: can't open file 'C:\\\\Users\\\\MCarek\\\\bh-rag\\\\Moje_Python_projekty\\\\spinoco-whisper\\\\main.py': [Errno 2] No such file or directory\n\n"
    }
  ],
  "notes": null
}